# Generated by Django 5.0.6 on 2024-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookstoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Sci_Fi', 'Sci_fi'), ('Humor', 'humor'), ('Horror', 'Horror')], max_length=30)),
                ('frist_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateField()),
            ],
        ),
    ]
